export const ddl = [
  `CREATE TABLE IF NOT EXISTS "user" (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    email_verified BOOLEAN NOT NULL,
    image TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "session" (
    id TEXT PRIMARY KEY,
    expires_at TIMESTAMP NOT NULL,
    token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "account" (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    access_token TEXT,
    refresh_token TEXT,
    id_token TEXT,
    access_token_expires_at TIMESTAMP,
    refresh_token_expires_at TIMESTAMP,
    scope TEXT,
    password TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "verification" (
    id TEXT PRIMARY KEY,
    identifier TEXT NOT NULL,
    value TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "organization" (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    logo_asset_id TEXT,
    metadata TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "biteship_areas" (
    area_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    subdistrict TEXT NOT NULL,
    district TEXT NOT NULL,
    city TEXT NOT NULL,
    province TEXT NOT NULL,
    postal_code TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "assets" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    draft_id TEXT,
    usage TEXT NOT NULL,
    asset_kind TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    uploaded_by_user_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    checksum_sha256 TEXT,
    image_width INTEGER,
    image_height INTEGER,
    video_duration_seconds INTEGER,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "asset_variants" (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL REFERENCES "assets"(id) ON DELETE CASCADE,
    variant_key TEXT NOT NULL,
    storage_key TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "organization_profiles" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL UNIQUE REFERENCES "organization"(id) ON DELETE CASCADE,
    display_name TEXT,
    phone TEXT,
    logo_asset_id TEXT REFERENCES "assets"(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "addresses" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    area_id TEXT REFERENCES "biteship_areas"(area_id) ON DELETE NO ACTION,
    area_name TEXT,
    street_address TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "member" (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "invitation" (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    role TEXT NOT NULL,
    status TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    inviter_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "customers" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    business_name TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    address_id TEXT REFERENCES "addresses"(id) ON DELETE SET NULL,
    is_wni BOOLEAN NOT NULL DEFAULT TRUE,
    photo_asset_id TEXT REFERENCES "assets"(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "products" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    production_notes TEXT,
    primary_image_asset_id TEXT REFERENCES "assets"(id) ON DELETE SET NULL,
    base_price INTEGER NOT NULL DEFAULT 0,
    production_days INTEGER NOT NULL DEFAULT 1,
    min_quantity INTEGER NOT NULL DEFAULT 1,
    max_quantity INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "product_variants" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES "products"(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    attributes TEXT DEFAULT '{}',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "pricing_breakpoints" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES "products"(id) ON DELETE CASCADE,
    variant_id TEXT REFERENCES "product_variants"(id) ON DELETE SET NULL,
    min_quantity INTEGER NOT NULL DEFAULT 1,
    unit_price REAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "orders" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    customer_id TEXT NOT NULL REFERENCES "customers"(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'draft',
    notes TEXT,
    total REAL NOT NULL DEFAULT 0,
    quote_number TEXT,
    valid_until TIMESTAMP,
    shipping_address JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "order_line_items" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    order_id TEXT NOT NULL REFERENCES "orders"(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES "products"(id) ON DELETE RESTRICT,
    variant_id TEXT REFERENCES "product_variants"(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price REAL NOT NULL,
    total REAL NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "customer_tokens" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    order_id TEXT NOT NULL REFERENCES "orders"(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    scope TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "invoices" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    order_id TEXT NOT NULL REFERENCES "orders"(id) ON DELETE RESTRICT,
    total REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    due_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "payments" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    invoice_id TEXT NOT NULL REFERENCES "invoices"(id) ON DELETE CASCADE,
    amount REAL NOT NULL,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reference TEXT,
    method TEXT NOT NULL DEFAULT 'bank_transfer',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "workflow_stages" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "production_tasks" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    order_id TEXT NOT NULL REFERENCES "orders"(id) ON DELETE CASCADE,
    stage_id TEXT NOT NULL REFERENCES "workflow_stages"(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'pending',
    context TEXT DEFAULT '{}',
    assigned_to TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "activity_events" (
    id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    actor_id TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    action TEXT NOT NULL,
    details TEXT DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
]
