/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrgRouteImport } from './routes/_org'
import { Route as OrgIndexRouteImport } from './routes/_org/index'
import { Route as OrgCustomersIndexRouteImport } from './routes/_org/customers/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgCustomersNewRouteImport } from './routes/_org/customers/new'
import { Route as OrgCustomersIdEditRouteImport } from './routes/_org/customers/$id/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCustomersIndexRoute = OrgCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => OrgRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCustomersNewRoute = OrgCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCustomersIdEditRoute = OrgCustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => OrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OrgIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/customers/new': typeof OrgCustomersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers/': typeof OrgCustomersIndexRoute
  '/customers/$id/edit': typeof OrgCustomersIdEditRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/': typeof OrgIndexRoute
  '/customers/new': typeof OrgCustomersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers': typeof OrgCustomersIndexRoute
  '/customers/$id/edit': typeof OrgCustomersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_org': typeof OrgRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_org/': typeof OrgIndexRoute
  '/_org/customers/new': typeof OrgCustomersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_org/customers/': typeof OrgCustomersIndexRoute
  '/_org/customers/$id/edit': typeof OrgCustomersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/customers/new'
    | '/api/auth/$'
    | '/customers/'
    | '/customers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/customers/new'
    | '/api/auth/$'
    | '/customers'
    | '/customers/$id/edit'
  id:
    | '__root__'
    | '/_org'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/_org/'
    | '/_org/customers/new'
    | '/api/auth/$'
    | '/_org/customers/'
    | '/_org/customers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrgRoute: typeof OrgRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org': {
      id: '/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/': {
      id: '/_org/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/customers/': {
      id: '/_org/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof OrgCustomersIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/customers/new': {
      id: '/_org/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof OrgCustomersNewRouteImport
      parentRoute: typeof OrgRoute
    }
    '/_org/customers/$id/edit': {
      id: '/_org/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof OrgCustomersIdEditRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgIndexRoute: typeof OrgIndexRoute
  OrgCustomersNewRoute: typeof OrgCustomersNewRoute
  OrgCustomersIndexRoute: typeof OrgCustomersIndexRoute
  OrgCustomersIdEditRoute: typeof OrgCustomersIdEditRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgIndexRoute: OrgIndexRoute,
  OrgCustomersNewRoute: OrgCustomersNewRoute,
  OrgCustomersIndexRoute: OrgCustomersIndexRoute,
  OrgCustomersIdEditRoute: OrgCustomersIdEditRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OrgRoute: OrgRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
